// Code generated by ent, DO NOT EDIT.

package financecurrentaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the financecurrentaccount type in the database.
	Label = "finance_current_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDeletedName holds the string denoting the deletedname field in the database.
	FieldDeletedName = "deleted_name"
	// FieldNationalIdentificationNumber holds the string denoting the nationalidentificationnumber field in the database.
	FieldNationalIdentificationNumber = "national_identification_number"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldTaxOffice holds the string denoting the taxoffice field in the database.
	FieldTaxOffice = "tax_office"
	// FieldTaxNumber holds the string denoting the taxnumber field in the database.
	FieldTaxNumber = "tax_number"
	// FieldBusinessPhone holds the string denoting the businessphone field in the database.
	FieldBusinessPhone = "business_phone"
	// FieldCellPhone holds the string denoting the cellphone field in the database.
	FieldCellPhone = "cell_phone"
	// FieldFax holds the string denoting the fax field in the database.
	FieldFax = "fax"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldWebAddress holds the string denoting the webaddress field in the database.
	FieldWebAddress = "web_address"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCompany holds the string denoting the company edge name in mutations.
	EdgeCompany = "company"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeOperations holds the string denoting the operations edge name in mutations.
	EdgeOperations = "operations"
	// EdgeAccountType holds the string denoting the account_type edge name in mutations.
	EdgeAccountType = "account_type"
	// Table holds the table name of the financecurrentaccount in the database.
	Table = "current_accounts"
	// CompanyTable is the table that holds the company relation/edge.
	CompanyTable = "current_accounts"
	// CompanyInverseTable is the table name for the CompanyDetail entity.
	// It exists in this package in order to avoid circular dependency with the "companydetail" package.
	CompanyInverseTable = "company_details"
	// CompanyColumn is the table column denoting the company relation/edge.
	CompanyColumn = "company_id"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "current_accounts"
	// GroupInverseTable is the table name for the FinanceCurrentAccountGroup entity.
	// It exists in this package in order to avoid circular dependency with the "financecurrentaccountgroup" package.
	GroupInverseTable = "current_account_groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// OperationsTable is the table that holds the operations relation/edge.
	OperationsTable = "current_account_operations"
	// OperationsInverseTable is the table name for the FinanceCurrentAccountOperation entity.
	// It exists in this package in order to avoid circular dependency with the "financecurrentaccountoperation" package.
	OperationsInverseTable = "current_account_operations"
	// OperationsColumn is the table column denoting the operations relation/edge.
	OperationsColumn = "account_id"
	// AccountTypeTable is the table that holds the account_type relation/edge.
	AccountTypeTable = "current_accounts"
	// AccountTypeInverseTable is the table name for the FinanceCurrentAccountType entity.
	// It exists in this package in order to avoid circular dependency with the "financecurrentaccounttype" package.
	AccountTypeInverseTable = "current_account_types"
	// AccountTypeColumn is the table column denoting the account_type relation/edge.
	AccountTypeColumn = "type_id"
)

// Columns holds all SQL columns for financecurrentaccount fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDeletedName,
	FieldNationalIdentificationNumber,
	FieldAddress,
	FieldTaxOffice,
	FieldTaxNumber,
	FieldBusinessPhone,
	FieldCellPhone,
	FieldFax,
	FieldEmail,
	FieldWebAddress,
	FieldNote,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "current_accounts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"company_id",
	"group_id",
	"type_id",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "Name" field.
	DefaultName string
	// DefaultStatus holds the default value on creation for the "Status" field.
	DefaultStatus bool
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updatedAt" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the FinanceCurrentAccount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the Name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDeletedName orders the results by the DeletedName field.
func ByDeletedName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedName, opts...).ToFunc()
}

// ByNationalIdentificationNumber orders the results by the NationalIdentificationNumber field.
func ByNationalIdentificationNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNationalIdentificationNumber, opts...).ToFunc()
}

// ByAddress orders the results by the Address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByTaxOffice orders the results by the TaxOffice field.
func ByTaxOffice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxOffice, opts...).ToFunc()
}

// ByTaxNumber orders the results by the TaxNumber field.
func ByTaxNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxNumber, opts...).ToFunc()
}

// ByBusinessPhone orders the results by the BusinessPhone field.
func ByBusinessPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBusinessPhone, opts...).ToFunc()
}

// ByCellPhone orders the results by the CellPhone field.
func ByCellPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCellPhone, opts...).ToFunc()
}

// ByFax orders the results by the Fax field.
func ByFax(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFax, opts...).ToFunc()
}

// ByEmail orders the results by the Email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByWebAddress orders the results by the WebAddress field.
func ByWebAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebAddress, opts...).ToFunc()
}

// ByNote orders the results by the Note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// ByStatus orders the results by the Status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCompanyField orders the results by company field.
func ByCompanyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCompanyStep(), sql.OrderByField(field, opts...))
	}
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByOperationsCount orders the results by operations count.
func ByOperationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOperationsStep(), opts...)
	}
}

// ByOperations orders the results by operations terms.
func ByOperations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOperationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAccountTypeField orders the results by account_type field.
func ByAccountTypeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountTypeStep(), sql.OrderByField(field, opts...))
	}
}
func newCompanyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CompanyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CompanyTable, CompanyColumn),
	)
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
func newOperationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OperationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OperationsTable, OperationsColumn),
	)
}
func newAccountTypeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountTypeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccountTypeTable, AccountTypeColumn),
	)
}
