// Code generated by ent, DO NOT EDIT.

package companypersonnel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/polatbilal/ent-gqlgen/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "Name" field. It's identical to NameEQ.
func Name(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldName, v))
}

// TcNo applies equality check predicate on the "TcNo" field. It's identical to TcNoEQ.
func TcNo(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldTcNo, v))
}

// Phone applies equality check predicate on the "Phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldPhone, v))
}

// Email applies equality check predicate on the "Email" field. It's identical to EmailEQ.
func Email(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldEmail, v))
}

// Address applies equality check predicate on the "Address" field. It's identical to AddressEQ.
func Address(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldAddress, v))
}

// Employment applies equality check predicate on the "Employment" field. It's identical to EmploymentEQ.
func Employment(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldEmployment, v))
}

// Status applies equality check predicate on the "Status" field. It's identical to StatusEQ.
func Status(v bool) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldStatus, v))
}

// Note applies equality check predicate on the "Note" field. It's identical to NoteEQ.
func Note(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldNote, v))
}

// CreatedAt applies equality check predicate on the "CreatedAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "UpdatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "Name" field.
func NameEQ(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "Name" field.
func NameNEQ(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "Name" field.
func NameIn(vs ...string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "Name" field.
func NameNotIn(vs ...string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "Name" field.
func NameGT(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "Name" field.
func NameGTE(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "Name" field.
func NameLT(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "Name" field.
func NameLTE(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "Name" field.
func NameContains(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "Name" field.
func NameHasPrefix(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "Name" field.
func NameHasSuffix(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "Name" field.
func NameEqualFold(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "Name" field.
func NameContainsFold(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldContainsFold(FieldName, v))
}

// TcNoEQ applies the EQ predicate on the "TcNo" field.
func TcNoEQ(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldTcNo, v))
}

// TcNoNEQ applies the NEQ predicate on the "TcNo" field.
func TcNoNEQ(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNEQ(FieldTcNo, v))
}

// TcNoIn applies the In predicate on the "TcNo" field.
func TcNoIn(vs ...string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldIn(FieldTcNo, vs...))
}

// TcNoNotIn applies the NotIn predicate on the "TcNo" field.
func TcNoNotIn(vs ...string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNotIn(FieldTcNo, vs...))
}

// TcNoGT applies the GT predicate on the "TcNo" field.
func TcNoGT(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGT(FieldTcNo, v))
}

// TcNoGTE applies the GTE predicate on the "TcNo" field.
func TcNoGTE(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGTE(FieldTcNo, v))
}

// TcNoLT applies the LT predicate on the "TcNo" field.
func TcNoLT(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLT(FieldTcNo, v))
}

// TcNoLTE applies the LTE predicate on the "TcNo" field.
func TcNoLTE(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLTE(FieldTcNo, v))
}

// TcNoContains applies the Contains predicate on the "TcNo" field.
func TcNoContains(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldContains(FieldTcNo, v))
}

// TcNoHasPrefix applies the HasPrefix predicate on the "TcNo" field.
func TcNoHasPrefix(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldHasPrefix(FieldTcNo, v))
}

// TcNoHasSuffix applies the HasSuffix predicate on the "TcNo" field.
func TcNoHasSuffix(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldHasSuffix(FieldTcNo, v))
}

// TcNoIsNil applies the IsNil predicate on the "TcNo" field.
func TcNoIsNil() predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldIsNull(FieldTcNo))
}

// TcNoNotNil applies the NotNil predicate on the "TcNo" field.
func TcNoNotNil() predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNotNull(FieldTcNo))
}

// TcNoEqualFold applies the EqualFold predicate on the "TcNo" field.
func TcNoEqualFold(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEqualFold(FieldTcNo, v))
}

// TcNoContainsFold applies the ContainsFold predicate on the "TcNo" field.
func TcNoContainsFold(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldContainsFold(FieldTcNo, v))
}

// PhoneEQ applies the EQ predicate on the "Phone" field.
func PhoneEQ(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "Phone" field.
func PhoneNEQ(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "Phone" field.
func PhoneIn(vs ...string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "Phone" field.
func PhoneNotIn(vs ...string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "Phone" field.
func PhoneGT(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "Phone" field.
func PhoneGTE(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "Phone" field.
func PhoneLT(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "Phone" field.
func PhoneLTE(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "Phone" field.
func PhoneContains(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "Phone" field.
func PhoneHasPrefix(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "Phone" field.
func PhoneHasSuffix(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneIsNil applies the IsNil predicate on the "Phone" field.
func PhoneIsNil() predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldIsNull(FieldPhone))
}

// PhoneNotNil applies the NotNil predicate on the "Phone" field.
func PhoneNotNil() predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNotNull(FieldPhone))
}

// PhoneEqualFold applies the EqualFold predicate on the "Phone" field.
func PhoneEqualFold(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "Phone" field.
func PhoneContainsFold(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldContainsFold(FieldPhone, v))
}

// EmailEQ applies the EQ predicate on the "Email" field.
func EmailEQ(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "Email" field.
func EmailNEQ(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "Email" field.
func EmailIn(vs ...string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "Email" field.
func EmailNotIn(vs ...string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "Email" field.
func EmailGT(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "Email" field.
func EmailGTE(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "Email" field.
func EmailLT(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "Email" field.
func EmailLTE(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "Email" field.
func EmailContains(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "Email" field.
func EmailHasPrefix(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "Email" field.
func EmailHasSuffix(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "Email" field.
func EmailIsNil() predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "Email" field.
func EmailNotNil() predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "Email" field.
func EmailEqualFold(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "Email" field.
func EmailContainsFold(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldContainsFold(FieldEmail, v))
}

// AddressEQ applies the EQ predicate on the "Address" field.
func AddressEQ(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "Address" field.
func AddressNEQ(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "Address" field.
func AddressIn(vs ...string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "Address" field.
func AddressNotIn(vs ...string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "Address" field.
func AddressGT(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "Address" field.
func AddressGTE(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "Address" field.
func AddressLT(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "Address" field.
func AddressLTE(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "Address" field.
func AddressContains(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "Address" field.
func AddressHasPrefix(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "Address" field.
func AddressHasSuffix(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressIsNil applies the IsNil predicate on the "Address" field.
func AddressIsNil() predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldIsNull(FieldAddress))
}

// AddressNotNil applies the NotNil predicate on the "Address" field.
func AddressNotNil() predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNotNull(FieldAddress))
}

// AddressEqualFold applies the EqualFold predicate on the "Address" field.
func AddressEqualFold(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "Address" field.
func AddressContainsFold(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldContainsFold(FieldAddress, v))
}

// EmploymentEQ applies the EQ predicate on the "Employment" field.
func EmploymentEQ(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldEmployment, v))
}

// EmploymentNEQ applies the NEQ predicate on the "Employment" field.
func EmploymentNEQ(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNEQ(FieldEmployment, v))
}

// EmploymentIn applies the In predicate on the "Employment" field.
func EmploymentIn(vs ...time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldIn(FieldEmployment, vs...))
}

// EmploymentNotIn applies the NotIn predicate on the "Employment" field.
func EmploymentNotIn(vs ...time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNotIn(FieldEmployment, vs...))
}

// EmploymentGT applies the GT predicate on the "Employment" field.
func EmploymentGT(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGT(FieldEmployment, v))
}

// EmploymentGTE applies the GTE predicate on the "Employment" field.
func EmploymentGTE(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGTE(FieldEmployment, v))
}

// EmploymentLT applies the LT predicate on the "Employment" field.
func EmploymentLT(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLT(FieldEmployment, v))
}

// EmploymentLTE applies the LTE predicate on the "Employment" field.
func EmploymentLTE(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLTE(FieldEmployment, v))
}

// EmploymentIsNil applies the IsNil predicate on the "Employment" field.
func EmploymentIsNil() predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldIsNull(FieldEmployment))
}

// EmploymentNotNil applies the NotNil predicate on the "Employment" field.
func EmploymentNotNil() predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNotNull(FieldEmployment))
}

// StatusEQ applies the EQ predicate on the "Status" field.
func StatusEQ(v bool) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "Status" field.
func StatusNEQ(v bool) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNEQ(FieldStatus, v))
}

// NoteEQ applies the EQ predicate on the "Note" field.
func NoteEQ(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "Note" field.
func NoteNEQ(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "Note" field.
func NoteIn(vs ...string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "Note" field.
func NoteNotIn(vs ...string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "Note" field.
func NoteGT(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "Note" field.
func NoteGTE(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "Note" field.
func NoteLT(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "Note" field.
func NoteLTE(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "Note" field.
func NoteContains(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "Note" field.
func NoteHasPrefix(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "Note" field.
func NoteHasSuffix(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "Note" field.
func NoteIsNil() predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "Note" field.
func NoteNotNil() predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "Note" field.
func NoteEqualFold(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "Note" field.
func NoteContainsFold(v string) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldContainsFold(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "CreatedAt" field.
func CreatedAtEQ(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "CreatedAt" field.
func CreatedAtNEQ(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "CreatedAt" field.
func CreatedAtIn(vs ...time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "CreatedAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "CreatedAt" field.
func CreatedAtGT(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "CreatedAt" field.
func CreatedAtGTE(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "CreatedAt" field.
func CreatedAtLT(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "CreatedAt" field.
func CreatedAtLTE(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "UpdatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "UpdatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "UpdatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "UpdatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "UpdatedAt" field.
func UpdatedAtGT(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "UpdatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "UpdatedAt" field.
func UpdatedAtLT(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "UpdatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasCompany applies the HasEdge predicate on the "company" edge.
func HasCompany() predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CompanyTable, CompanyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCompanyWith applies the HasEdge predicate on the "company" edge with a given conditions (other predicates).
func HasCompanyWith(preds ...predicate.CompanyDetail) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(func(s *sql.Selector) {
		step := newCompanyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFinanceRelations applies the HasEdge predicate on the "finance_relations" edge.
func HasFinanceRelations() predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FinanceRelationsTable, FinanceRelationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFinanceRelationsWith applies the HasEdge predicate on the "finance_relations" edge with a given conditions (other predicates).
func HasFinanceRelationsWith(preds ...predicate.FinanceRelations) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(func(s *sql.Selector) {
		step := newFinanceRelationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CompanyPersonnel) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CompanyPersonnel) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CompanyPersonnel) predicate.CompanyPersonnel {
	return predicate.CompanyPersonnel(sql.NotPredicates(p))
}
