// Code generated by ent, DO NOT EDIT.

package financecashaccountoperation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/polatbilal/ent-gqlgen/ent/predicate"
	"github.com/shopspring/decimal"

	"github.com/polatbilal/ent-gqlgen/ent/internal"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldLTE(FieldID, id))
}

// Date applies equality check predicate on the "Date" field. It's identical to DateEQ.
func Date(v time.Time) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldEQ(FieldDate, v))
}

// Debit applies equality check predicate on the "Debit" field. It's identical to DebitEQ.
func Debit(v *decimal.NullDecimal) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldEQ(FieldDebit, v))
}

// Credit applies equality check predicate on the "Credit" field. It's identical to CreditEQ.
func Credit(v *decimal.NullDecimal) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldEQ(FieldCredit, v))
}

// Description applies equality check predicate on the "Description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldEQ(FieldDescription, v))
}

// Status applies equality check predicate on the "Status" field. It's identical to StatusEQ.
func Status(v bool) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldEQ(FieldStatus, v))
}

// DateEQ applies the EQ predicate on the "Date" field.
func DateEQ(v time.Time) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "Date" field.
func DateNEQ(v time.Time) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "Date" field.
func DateIn(vs ...time.Time) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "Date" field.
func DateNotIn(vs ...time.Time) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "Date" field.
func DateGT(v time.Time) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "Date" field.
func DateGTE(v time.Time) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "Date" field.
func DateLT(v time.Time) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "Date" field.
func DateLTE(v time.Time) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldLTE(FieldDate, v))
}

// DebitEQ applies the EQ predicate on the "Debit" field.
func DebitEQ(v *decimal.NullDecimal) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldEQ(FieldDebit, v))
}

// DebitNEQ applies the NEQ predicate on the "Debit" field.
func DebitNEQ(v *decimal.NullDecimal) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldNEQ(FieldDebit, v))
}

// DebitIn applies the In predicate on the "Debit" field.
func DebitIn(vs ...*decimal.NullDecimal) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldIn(FieldDebit, vs...))
}

// DebitNotIn applies the NotIn predicate on the "Debit" field.
func DebitNotIn(vs ...*decimal.NullDecimal) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldNotIn(FieldDebit, vs...))
}

// DebitGT applies the GT predicate on the "Debit" field.
func DebitGT(v *decimal.NullDecimal) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldGT(FieldDebit, v))
}

// DebitGTE applies the GTE predicate on the "Debit" field.
func DebitGTE(v *decimal.NullDecimal) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldGTE(FieldDebit, v))
}

// DebitLT applies the LT predicate on the "Debit" field.
func DebitLT(v *decimal.NullDecimal) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldLT(FieldDebit, v))
}

// DebitLTE applies the LTE predicate on the "Debit" field.
func DebitLTE(v *decimal.NullDecimal) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldLTE(FieldDebit, v))
}

// DebitIsNil applies the IsNil predicate on the "Debit" field.
func DebitIsNil() predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldIsNull(FieldDebit))
}

// DebitNotNil applies the NotNil predicate on the "Debit" field.
func DebitNotNil() predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldNotNull(FieldDebit))
}

// CreditEQ applies the EQ predicate on the "Credit" field.
func CreditEQ(v *decimal.NullDecimal) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldEQ(FieldCredit, v))
}

// CreditNEQ applies the NEQ predicate on the "Credit" field.
func CreditNEQ(v *decimal.NullDecimal) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldNEQ(FieldCredit, v))
}

// CreditIn applies the In predicate on the "Credit" field.
func CreditIn(vs ...*decimal.NullDecimal) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldIn(FieldCredit, vs...))
}

// CreditNotIn applies the NotIn predicate on the "Credit" field.
func CreditNotIn(vs ...*decimal.NullDecimal) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldNotIn(FieldCredit, vs...))
}

// CreditGT applies the GT predicate on the "Credit" field.
func CreditGT(v *decimal.NullDecimal) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldGT(FieldCredit, v))
}

// CreditGTE applies the GTE predicate on the "Credit" field.
func CreditGTE(v *decimal.NullDecimal) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldGTE(FieldCredit, v))
}

// CreditLT applies the LT predicate on the "Credit" field.
func CreditLT(v *decimal.NullDecimal) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldLT(FieldCredit, v))
}

// CreditLTE applies the LTE predicate on the "Credit" field.
func CreditLTE(v *decimal.NullDecimal) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldLTE(FieldCredit, v))
}

// CreditIsNil applies the IsNil predicate on the "Credit" field.
func CreditIsNil() predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldIsNull(FieldCredit))
}

// CreditNotNil applies the NotNil predicate on the "Credit" field.
func CreditNotNil() predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldNotNull(FieldCredit))
}

// DescriptionEQ applies the EQ predicate on the "Description" field.
func DescriptionEQ(v string) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "Description" field.
func DescriptionNEQ(v string) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "Description" field.
func DescriptionIn(vs ...string) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "Description" field.
func DescriptionNotIn(vs ...string) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "Description" field.
func DescriptionGT(v string) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "Description" field.
func DescriptionGTE(v string) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "Description" field.
func DescriptionLT(v string) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "Description" field.
func DescriptionLTE(v string) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "Description" field.
func DescriptionContains(v string) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "Description" field.
func DescriptionHasPrefix(v string) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "Description" field.
func DescriptionHasSuffix(v string) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "Description" field.
func DescriptionEqualFold(v string) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "Description" field.
func DescriptionContainsFold(v string) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldContainsFold(FieldDescription, v))
}

// StatusEQ applies the EQ predicate on the "Status" field.
func StatusEQ(v bool) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "Status" field.
func StatusNEQ(v bool) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.FieldNEQ(FieldStatus, v))
}

// HasCompany applies the HasEdge predicate on the "company" edge.
func HasCompany() predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CompanyTable, CompanyColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.CompanyDetail
		step.Edge.Schema = schemaConfig.FinanceCashAccountOperation
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCompanyWith applies the HasEdge predicate on the "company" edge with a given conditions (other predicates).
func HasCompanyWith(preds ...predicate.CompanyDetail) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(func(s *sql.Selector) {
		step := newCompanyStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.CompanyDetail
		step.Edge.Schema = schemaConfig.FinanceCashAccountOperation
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCashAccount applies the HasEdge predicate on the "cash_account" edge.
func HasCashAccount() predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CashAccountTable, CashAccountColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.FinanceCashAccount
		step.Edge.Schema = schemaConfig.FinanceCashAccountOperation
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCashAccountWith applies the HasEdge predicate on the "cash_account" edge with a given conditions (other predicates).
func HasCashAccountWith(preds ...predicate.FinanceCashAccount) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(func(s *sql.Selector) {
		step := newCashAccountStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.FinanceCashAccount
		step.Edge.Schema = schemaConfig.FinanceCashAccountOperation
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOperationGroup applies the HasEdge predicate on the "operation_group" edge.
func HasOperationGroup() predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OperationGroupTable, OperationGroupColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.FinanceOperationGroup
		step.Edge.Schema = schemaConfig.FinanceCashAccountOperation
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOperationGroupWith applies the HasEdge predicate on the "operation_group" edge with a given conditions (other predicates).
func HasOperationGroupWith(preds ...predicate.FinanceOperationGroup) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(func(s *sql.Selector) {
		step := newOperationGroupStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.FinanceOperationGroup
		step.Edge.Schema = schemaConfig.FinanceCashAccountOperation
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPaymentClass applies the HasEdge predicate on the "payment_class" edge.
func HasPaymentClass() predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PaymentClassTable, PaymentClassColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.FinancePaymentClass
		step.Edge.Schema = schemaConfig.FinanceCashAccountOperation
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPaymentClassWith applies the HasEdge predicate on the "payment_class" edge with a given conditions (other predicates).
func HasPaymentClassWith(preds ...predicate.FinancePaymentClass) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(func(s *sql.Selector) {
		step := newPaymentClassStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.FinancePaymentClass
		step.Edge.Schema = schemaConfig.FinanceCashAccountOperation
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasParticipantCurrentOperation applies the HasEdge predicate on the "participant_current_operation" edge.
func HasParticipantCurrentOperation() predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ParticipantCurrentOperationTable, ParticipantCurrentOperationColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.FinanceCurrentAccountOperation
		step.Edge.Schema = schemaConfig.FinanceCashAccountOperation
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParticipantCurrentOperationWith applies the HasEdge predicate on the "participant_current_operation" edge with a given conditions (other predicates).
func HasParticipantCurrentOperationWith(preds ...predicate.FinanceCurrentAccountOperation) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(func(s *sql.Selector) {
		step := newParticipantCurrentOperationStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.FinanceCurrentAccountOperation
		step.Edge.Schema = schemaConfig.FinanceCashAccountOperation
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasParticipantBankOperation applies the HasEdge predicate on the "participant_bank_operation" edge.
func HasParticipantBankOperation() predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ParticipantBankOperationTable, ParticipantBankOperationColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.FinanceBankOperation
		step.Edge.Schema = schemaConfig.FinanceCashAccountOperation
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParticipantBankOperationWith applies the HasEdge predicate on the "participant_bank_operation" edge with a given conditions (other predicates).
func HasParticipantBankOperationWith(preds ...predicate.FinanceBankOperation) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(func(s *sql.Selector) {
		step := newParticipantBankOperationStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.FinanceBankOperation
		step.Edge.Schema = schemaConfig.FinanceCashAccountOperation
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBankParticipant applies the HasEdge predicate on the "bank_participant" edge.
func HasBankParticipant() predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, BankParticipantTable, BankParticipantColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.FinanceBankOperation
		step.Edge.Schema = schemaConfig.FinanceBankOperation
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBankParticipantWith applies the HasEdge predicate on the "bank_participant" edge with a given conditions (other predicates).
func HasBankParticipantWith(preds ...predicate.FinanceBankOperation) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(func(s *sql.Selector) {
		step := newBankParticipantStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.FinanceBankOperation
		step.Edge.Schema = schemaConfig.FinanceBankOperation
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FinanceCashAccountOperation) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FinanceCashAccountOperation) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FinanceCashAccountOperation) predicate.FinanceCashAccountOperation {
	return predicate.FinanceCashAccountOperation(sql.NotPredicates(p))
}
