// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/polatbilal/ent-gqlgen/ent/companydetail"
	"github.com/polatbilal/ent-gqlgen/ent/companyengineer"
	"github.com/polatbilal/ent-gqlgen/ent/jobrelations"
)

// CompanyEngineerCreate is the builder for creating a CompanyEngineer entity.
type CompanyEngineerCreate struct {
	config
	mutation *CompanyEngineerMutation
	hooks    []Hook
}

// SetName sets the "Name" field.
func (_c *CompanyEngineerCreate) SetName(v string) *CompanyEngineerCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (_c *CompanyEngineerCreate) SetNillableName(v *string) *CompanyEngineerCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetTcNo sets the "TcNo" field.
func (_c *CompanyEngineerCreate) SetTcNo(v string) *CompanyEngineerCreate {
	_c.mutation.SetTcNo(v)
	return _c
}

// SetNillableTcNo sets the "TcNo" field if the given value is not nil.
func (_c *CompanyEngineerCreate) SetNillableTcNo(v *string) *CompanyEngineerCreate {
	if v != nil {
		_c.SetTcNo(*v)
	}
	return _c
}

// SetPhone sets the "Phone" field.
func (_c *CompanyEngineerCreate) SetPhone(v string) *CompanyEngineerCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "Phone" field if the given value is not nil.
func (_c *CompanyEngineerCreate) SetNillablePhone(v *string) *CompanyEngineerCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetEmail sets the "Email" field.
func (_c *CompanyEngineerCreate) SetEmail(v string) *CompanyEngineerCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "Email" field if the given value is not nil.
func (_c *CompanyEngineerCreate) SetNillableEmail(v *string) *CompanyEngineerCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetAddress sets the "Address" field.
func (_c *CompanyEngineerCreate) SetAddress(v string) *CompanyEngineerCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetNillableAddress sets the "Address" field if the given value is not nil.
func (_c *CompanyEngineerCreate) SetNillableAddress(v *string) *CompanyEngineerCreate {
	if v != nil {
		_c.SetAddress(*v)
	}
	return _c
}

// SetCareer sets the "Career" field.
func (_c *CompanyEngineerCreate) SetCareer(v string) *CompanyEngineerCreate {
	_c.mutation.SetCareer(v)
	return _c
}

// SetNillableCareer sets the "Career" field if the given value is not nil.
func (_c *CompanyEngineerCreate) SetNillableCareer(v *string) *CompanyEngineerCreate {
	if v != nil {
		_c.SetCareer(*v)
	}
	return _c
}

// SetPosition sets the "Position" field.
func (_c *CompanyEngineerCreate) SetPosition(v string) *CompanyEngineerCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetNillablePosition sets the "Position" field if the given value is not nil.
func (_c *CompanyEngineerCreate) SetNillablePosition(v *string) *CompanyEngineerCreate {
	if v != nil {
		_c.SetPosition(*v)
	}
	return _c
}

// SetRegisterNo sets the "RegisterNo" field.
func (_c *CompanyEngineerCreate) SetRegisterNo(v string) *CompanyEngineerCreate {
	_c.mutation.SetRegisterNo(v)
	return _c
}

// SetNillableRegisterNo sets the "RegisterNo" field if the given value is not nil.
func (_c *CompanyEngineerCreate) SetNillableRegisterNo(v *string) *CompanyEngineerCreate {
	if v != nil {
		_c.SetRegisterNo(*v)
	}
	return _c
}

// SetCertNo sets the "CertNo" field.
func (_c *CompanyEngineerCreate) SetCertNo(v string) *CompanyEngineerCreate {
	_c.mutation.SetCertNo(v)
	return _c
}

// SetNillableCertNo sets the "CertNo" field if the given value is not nil.
func (_c *CompanyEngineerCreate) SetNillableCertNo(v *string) *CompanyEngineerCreate {
	if v != nil {
		_c.SetCertNo(*v)
	}
	return _c
}

// SetYDSID sets the "YDSID" field.
func (_c *CompanyEngineerCreate) SetYDSID(v int) *CompanyEngineerCreate {
	_c.mutation.SetYDSID(v)
	return _c
}

// SetNillableYDSID sets the "YDSID" field if the given value is not nil.
func (_c *CompanyEngineerCreate) SetNillableYDSID(v *int) *CompanyEngineerCreate {
	if v != nil {
		_c.SetYDSID(*v)
	}
	return _c
}

// SetEmployment sets the "Employment" field.
func (_c *CompanyEngineerCreate) SetEmployment(v time.Time) *CompanyEngineerCreate {
	_c.mutation.SetEmployment(v)
	return _c
}

// SetNillableEmployment sets the "Employment" field if the given value is not nil.
func (_c *CompanyEngineerCreate) SetNillableEmployment(v *time.Time) *CompanyEngineerCreate {
	if v != nil {
		_c.SetEmployment(*v)
	}
	return _c
}

// SetStatus sets the "Status" field.
func (_c *CompanyEngineerCreate) SetStatus(v int) *CompanyEngineerCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "Status" field if the given value is not nil.
func (_c *CompanyEngineerCreate) SetNillableStatus(v *int) *CompanyEngineerCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetNote sets the "Note" field.
func (_c *CompanyEngineerCreate) SetNote(v string) *CompanyEngineerCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "Note" field if the given value is not nil.
func (_c *CompanyEngineerCreate) SetNillableNote(v *string) *CompanyEngineerCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetCreatedAt sets the "CreatedAt" field.
func (_c *CompanyEngineerCreate) SetCreatedAt(v time.Time) *CompanyEngineerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "CreatedAt" field if the given value is not nil.
func (_c *CompanyEngineerCreate) SetNillableCreatedAt(v *time.Time) *CompanyEngineerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "UpdatedAt" field.
func (_c *CompanyEngineerCreate) SetUpdatedAt(v time.Time) *CompanyEngineerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "UpdatedAt" field if the given value is not nil.
func (_c *CompanyEngineerCreate) SetNillableUpdatedAt(v *time.Time) *CompanyEngineerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCompanyID sets the "company" edge to the CompanyDetail entity by ID.
func (_c *CompanyEngineerCreate) SetCompanyID(id int) *CompanyEngineerCreate {
	_c.mutation.SetCompanyID(id)
	return _c
}

// SetNillableCompanyID sets the "company" edge to the CompanyDetail entity by ID if the given value is not nil.
func (_c *CompanyEngineerCreate) SetNillableCompanyID(id *int) *CompanyEngineerCreate {
	if id != nil {
		_c = _c.SetCompanyID(*id)
	}
	return _c
}

// SetCompany sets the "company" edge to the CompanyDetail entity.
func (_c *CompanyEngineerCreate) SetCompany(v *CompanyDetail) *CompanyEngineerCreate {
	return _c.SetCompanyID(v.ID)
}

// AddStaticIDs adds the "statics" edge to the JobRelations entity by IDs.
func (_c *CompanyEngineerCreate) AddStaticIDs(ids ...int) *CompanyEngineerCreate {
	_c.mutation.AddStaticIDs(ids...)
	return _c
}

// AddStatics adds the "statics" edges to the JobRelations entity.
func (_c *CompanyEngineerCreate) AddStatics(v ...*JobRelations) *CompanyEngineerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddStaticIDs(ids...)
}

// AddMechanicIDs adds the "mechanics" edge to the JobRelations entity by IDs.
func (_c *CompanyEngineerCreate) AddMechanicIDs(ids ...int) *CompanyEngineerCreate {
	_c.mutation.AddMechanicIDs(ids...)
	return _c
}

// AddMechanics adds the "mechanics" edges to the JobRelations entity.
func (_c *CompanyEngineerCreate) AddMechanics(v ...*JobRelations) *CompanyEngineerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMechanicIDs(ids...)
}

// AddElectricIDs adds the "electrics" edge to the JobRelations entity by IDs.
func (_c *CompanyEngineerCreate) AddElectricIDs(ids ...int) *CompanyEngineerCreate {
	_c.mutation.AddElectricIDs(ids...)
	return _c
}

// AddElectrics adds the "electrics" edges to the JobRelations entity.
func (_c *CompanyEngineerCreate) AddElectrics(v ...*JobRelations) *CompanyEngineerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddElectricIDs(ids...)
}

// AddInspectorIDs adds the "inspectors" edge to the JobRelations entity by IDs.
func (_c *CompanyEngineerCreate) AddInspectorIDs(ids ...int) *CompanyEngineerCreate {
	_c.mutation.AddInspectorIDs(ids...)
	return _c
}

// AddInspectors adds the "inspectors" edges to the JobRelations entity.
func (_c *CompanyEngineerCreate) AddInspectors(v ...*JobRelations) *CompanyEngineerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInspectorIDs(ids...)
}

// AddArchitectIDs adds the "architects" edge to the JobRelations entity by IDs.
func (_c *CompanyEngineerCreate) AddArchitectIDs(ids ...int) *CompanyEngineerCreate {
	_c.mutation.AddArchitectIDs(ids...)
	return _c
}

// AddArchitects adds the "architects" edges to the JobRelations entity.
func (_c *CompanyEngineerCreate) AddArchitects(v ...*JobRelations) *CompanyEngineerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddArchitectIDs(ids...)
}

// AddControllerIDs adds the "controllers" edge to the JobRelations entity by IDs.
func (_c *CompanyEngineerCreate) AddControllerIDs(ids ...int) *CompanyEngineerCreate {
	_c.mutation.AddControllerIDs(ids...)
	return _c
}

// AddControllers adds the "controllers" edges to the JobRelations entity.
func (_c *CompanyEngineerCreate) AddControllers(v ...*JobRelations) *CompanyEngineerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddControllerIDs(ids...)
}

// AddMechaniccontrollerIDs adds the "mechaniccontrollers" edge to the JobRelations entity by IDs.
func (_c *CompanyEngineerCreate) AddMechaniccontrollerIDs(ids ...int) *CompanyEngineerCreate {
	_c.mutation.AddMechaniccontrollerIDs(ids...)
	return _c
}

// AddMechaniccontrollers adds the "mechaniccontrollers" edges to the JobRelations entity.
func (_c *CompanyEngineerCreate) AddMechaniccontrollers(v ...*JobRelations) *CompanyEngineerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMechaniccontrollerIDs(ids...)
}

// AddElectriccontrollerIDs adds the "electriccontrollers" edge to the JobRelations entity by IDs.
func (_c *CompanyEngineerCreate) AddElectriccontrollerIDs(ids ...int) *CompanyEngineerCreate {
	_c.mutation.AddElectriccontrollerIDs(ids...)
	return _c
}

// AddElectriccontrollers adds the "electriccontrollers" edges to the JobRelations entity.
func (_c *CompanyEngineerCreate) AddElectriccontrollers(v ...*JobRelations) *CompanyEngineerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddElectriccontrollerIDs(ids...)
}

// Mutation returns the CompanyEngineerMutation object of the builder.
func (_c *CompanyEngineerCreate) Mutation() *CompanyEngineerMutation {
	return _c.mutation
}

// Save creates the CompanyEngineer in the database.
func (_c *CompanyEngineerCreate) Save(ctx context.Context) (*CompanyEngineer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CompanyEngineerCreate) SaveX(ctx context.Context) *CompanyEngineer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CompanyEngineerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CompanyEngineerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CompanyEngineerCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := companyengineer.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := companyengineer.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := companyengineer.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := companyengineer.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CompanyEngineerCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "Name", err: errors.New(`ent: missing required field "CompanyEngineer.Name"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "Status", err: errors.New(`ent: missing required field "CompanyEngineer.Status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "CreatedAt", err: errors.New(`ent: missing required field "CompanyEngineer.CreatedAt"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "UpdatedAt", err: errors.New(`ent: missing required field "CompanyEngineer.UpdatedAt"`)}
	}
	return nil
}

func (_c *CompanyEngineerCreate) sqlSave(ctx context.Context) (*CompanyEngineer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CompanyEngineerCreate) createSpec() (*CompanyEngineer, *sqlgraph.CreateSpec) {
	var (
		_node = &CompanyEngineer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(companyengineer.Table, sqlgraph.NewFieldSpec(companyengineer.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(companyengineer.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.TcNo(); ok {
		_spec.SetField(companyengineer.FieldTcNo, field.TypeString, value)
		_node.TcNo = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(companyengineer.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(companyengineer.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(companyengineer.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.Career(); ok {
		_spec.SetField(companyengineer.FieldCareer, field.TypeString, value)
		_node.Career = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(companyengineer.FieldPosition, field.TypeString, value)
		_node.Position = value
	}
	if value, ok := _c.mutation.RegisterNo(); ok {
		_spec.SetField(companyengineer.FieldRegisterNo, field.TypeString, value)
		_node.RegisterNo = value
	}
	if value, ok := _c.mutation.CertNo(); ok {
		_spec.SetField(companyengineer.FieldCertNo, field.TypeString, value)
		_node.CertNo = value
	}
	if value, ok := _c.mutation.YDSID(); ok {
		_spec.SetField(companyengineer.FieldYDSID, field.TypeInt, value)
		_node.YDSID = value
	}
	if value, ok := _c.mutation.Employment(); ok {
		_spec.SetField(companyengineer.FieldEmployment, field.TypeTime, value)
		_node.Employment = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(companyengineer.FieldStatus, field.TypeInt, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(companyengineer.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(companyengineer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(companyengineer.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CompanyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   companyengineer.CompanyTable,
			Columns: []string{companyengineer.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(companydetail.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.company_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StaticsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   companyengineer.StaticsTable,
			Columns: []string{companyengineer.StaticsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jobrelations.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MechanicsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   companyengineer.MechanicsTable,
			Columns: []string{companyengineer.MechanicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jobrelations.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ElectricsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   companyengineer.ElectricsTable,
			Columns: []string{companyengineer.ElectricsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jobrelations.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InspectorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   companyengineer.InspectorsTable,
			Columns: []string{companyengineer.InspectorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jobrelations.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ArchitectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   companyengineer.ArchitectsTable,
			Columns: []string{companyengineer.ArchitectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jobrelations.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ControllersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   companyengineer.ControllersTable,
			Columns: []string{companyengineer.ControllersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jobrelations.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MechaniccontrollersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   companyengineer.MechaniccontrollersTable,
			Columns: []string{companyengineer.MechaniccontrollersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jobrelations.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ElectriccontrollersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   companyengineer.ElectriccontrollersTable,
			Columns: []string{companyengineer.ElectriccontrollersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jobrelations.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CompanyEngineerCreateBulk is the builder for creating many CompanyEngineer entities in bulk.
type CompanyEngineerCreateBulk struct {
	config
	err      error
	builders []*CompanyEngineerCreate
}

// Save creates the CompanyEngineer entities in the database.
func (_c *CompanyEngineerCreateBulk) Save(ctx context.Context) ([]*CompanyEngineer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CompanyEngineer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CompanyEngineerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CompanyEngineerCreateBulk) SaveX(ctx context.Context) []*CompanyEngineer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CompanyEngineerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CompanyEngineerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
