// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/polatbilal/ent-gqlgen/ent/companydetail"
	"github.com/polatbilal/ent-gqlgen/ent/financecurrentaccount"
	"github.com/polatbilal/ent-gqlgen/ent/financecurrentaccounttype"
)

// FinanceCurrentAccountTypeCreate is the builder for creating a FinanceCurrentAccountType entity.
type FinanceCurrentAccountTypeCreate struct {
	config
	mutation *FinanceCurrentAccountTypeMutation
	hooks    []Hook
}

// SetDescription sets the "Description" field.
func (_c *FinanceCurrentAccountTypeCreate) SetDescription(v string) *FinanceCurrentAccountTypeCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "Description" field if the given value is not nil.
func (_c *FinanceCurrentAccountTypeCreate) SetNillableDescription(v *string) *FinanceCurrentAccountTypeCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetDeletedDescription sets the "DeletedDescription" field.
func (_c *FinanceCurrentAccountTypeCreate) SetDeletedDescription(v string) *FinanceCurrentAccountTypeCreate {
	_c.mutation.SetDeletedDescription(v)
	return _c
}

// SetNillableDeletedDescription sets the "DeletedDescription" field if the given value is not nil.
func (_c *FinanceCurrentAccountTypeCreate) SetNillableDeletedDescription(v *string) *FinanceCurrentAccountTypeCreate {
	if v != nil {
		_c.SetDeletedDescription(*v)
	}
	return _c
}

// SetDeletedDate sets the "DeletedDate" field.
func (_c *FinanceCurrentAccountTypeCreate) SetDeletedDate(v time.Time) *FinanceCurrentAccountTypeCreate {
	_c.mutation.SetDeletedDate(v)
	return _c
}

// SetNillableDeletedDate sets the "DeletedDate" field if the given value is not nil.
func (_c *FinanceCurrentAccountTypeCreate) SetNillableDeletedDate(v *time.Time) *FinanceCurrentAccountTypeCreate {
	if v != nil {
		_c.SetDeletedDate(*v)
	}
	return _c
}

// SetStatus sets the "Status" field.
func (_c *FinanceCurrentAccountTypeCreate) SetStatus(v bool) *FinanceCurrentAccountTypeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "Status" field if the given value is not nil.
func (_c *FinanceCurrentAccountTypeCreate) SetNillableStatus(v *bool) *FinanceCurrentAccountTypeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCompanyID sets the "company" edge to the CompanyDetail entity by ID.
func (_c *FinanceCurrentAccountTypeCreate) SetCompanyID(id int) *FinanceCurrentAccountTypeCreate {
	_c.mutation.SetCompanyID(id)
	return _c
}

// SetNillableCompanyID sets the "company" edge to the CompanyDetail entity by ID if the given value is not nil.
func (_c *FinanceCurrentAccountTypeCreate) SetNillableCompanyID(id *int) *FinanceCurrentAccountTypeCreate {
	if id != nil {
		_c = _c.SetCompanyID(*id)
	}
	return _c
}

// SetCompany sets the "company" edge to the CompanyDetail entity.
func (_c *FinanceCurrentAccountTypeCreate) SetCompany(v *CompanyDetail) *FinanceCurrentAccountTypeCreate {
	return _c.SetCompanyID(v.ID)
}

// AddCurrentAccountIDs adds the "current_accounts" edge to the FinanceCurrentAccount entity by IDs.
func (_c *FinanceCurrentAccountTypeCreate) AddCurrentAccountIDs(ids ...int) *FinanceCurrentAccountTypeCreate {
	_c.mutation.AddCurrentAccountIDs(ids...)
	return _c
}

// AddCurrentAccounts adds the "current_accounts" edges to the FinanceCurrentAccount entity.
func (_c *FinanceCurrentAccountTypeCreate) AddCurrentAccounts(v ...*FinanceCurrentAccount) *FinanceCurrentAccountTypeCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCurrentAccountIDs(ids...)
}

// Mutation returns the FinanceCurrentAccountTypeMutation object of the builder.
func (_c *FinanceCurrentAccountTypeCreate) Mutation() *FinanceCurrentAccountTypeMutation {
	return _c.mutation
}

// Save creates the FinanceCurrentAccountType in the database.
func (_c *FinanceCurrentAccountTypeCreate) Save(ctx context.Context) (*FinanceCurrentAccountType, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FinanceCurrentAccountTypeCreate) SaveX(ctx context.Context) *FinanceCurrentAccountType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FinanceCurrentAccountTypeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FinanceCurrentAccountTypeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FinanceCurrentAccountTypeCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := financecurrentaccounttype.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := financecurrentaccounttype.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FinanceCurrentAccountTypeCreate) check() error {
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "Description", err: errors.New(`ent: missing required field "FinanceCurrentAccountType.Description"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "Status", err: errors.New(`ent: missing required field "FinanceCurrentAccountType.Status"`)}
	}
	return nil
}

func (_c *FinanceCurrentAccountTypeCreate) sqlSave(ctx context.Context) (*FinanceCurrentAccountType, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FinanceCurrentAccountTypeCreate) createSpec() (*FinanceCurrentAccountType, *sqlgraph.CreateSpec) {
	var (
		_node = &FinanceCurrentAccountType{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(financecurrentaccounttype.Table, sqlgraph.NewFieldSpec(financecurrentaccounttype.FieldID, field.TypeInt))
	)
	_spec.Schema = _c.schemaConfig.FinanceCurrentAccountType
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(financecurrentaccounttype.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.DeletedDescription(); ok {
		_spec.SetField(financecurrentaccounttype.FieldDeletedDescription, field.TypeString, value)
		_node.DeletedDescription = value
	}
	if value, ok := _c.mutation.DeletedDate(); ok {
		_spec.SetField(financecurrentaccounttype.FieldDeletedDate, field.TypeTime, value)
		_node.DeletedDate = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(financecurrentaccounttype.FieldStatus, field.TypeBool, value)
		_node.Status = value
	}
	if nodes := _c.mutation.CompanyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   financecurrentaccounttype.CompanyTable,
			Columns: []string{financecurrentaccounttype.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(companydetail.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _c.schemaConfig.FinanceCurrentAccountType
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.company_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CurrentAccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   financecurrentaccounttype.CurrentAccountsTable,
			Columns: []string{financecurrentaccounttype.CurrentAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financecurrentaccount.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _c.schemaConfig.FinanceCurrentAccount
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FinanceCurrentAccountTypeCreateBulk is the builder for creating many FinanceCurrentAccountType entities in bulk.
type FinanceCurrentAccountTypeCreateBulk struct {
	config
	err      error
	builders []*FinanceCurrentAccountTypeCreate
}

// Save creates the FinanceCurrentAccountType entities in the database.
func (_c *FinanceCurrentAccountTypeCreateBulk) Save(ctx context.Context) ([]*FinanceCurrentAccountType, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FinanceCurrentAccountType, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FinanceCurrentAccountTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FinanceCurrentAccountTypeCreateBulk) SaveX(ctx context.Context) []*FinanceCurrentAccountType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FinanceCurrentAccountTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FinanceCurrentAccountTypeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
