// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/polatbilal/ent-gqlgen/ent/financeresource"
	"github.com/polatbilal/ent-gqlgen/ent/predicate"
)

// FinanceResourceDelete is the builder for deleting a FinanceResource entity.
type FinanceResourceDelete struct {
	config
	hooks    []Hook
	mutation *FinanceResourceMutation
}

// Where appends a list predicates to the FinanceResourceDelete builder.
func (_d *FinanceResourceDelete) Where(ps ...predicate.FinanceResource) *FinanceResourceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *FinanceResourceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FinanceResourceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *FinanceResourceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(financeresource.Table, sqlgraph.NewFieldSpec(financeresource.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// FinanceResourceDeleteOne is the builder for deleting a single FinanceResource entity.
type FinanceResourceDeleteOne struct {
	_d *FinanceResourceDelete
}

// Where appends a list predicates to the FinanceResourceDelete builder.
func (_d *FinanceResourceDeleteOne) Where(ps ...predicate.FinanceResource) *FinanceResourceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *FinanceResourceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{financeresource.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FinanceResourceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
