// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/polatbilal/ent-gqlgen/ent/companydetail"
	"github.com/polatbilal/ent-gqlgen/ent/financeclass"
)

// FinanceClass is the model entity for the FinanceClass schema.
type FinanceClass struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Category holds the value of the "Category" field.
	Category string `json:"Category,omitempty"`
	// Name holds the value of the "Name" field.
	Name string `json:"Name,omitempty"`
	// DeletedName holds the value of the "DeletedName" field.
	DeletedName string `json:"DeletedName,omitempty"`
	// DeletedDate holds the value of the "DeletedDate" field.
	DeletedDate time.Time `json:"DeletedDate,omitempty"`
	// Status holds the value of the "Status" field.
	Status bool `json:"Status,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FinanceClassQuery when eager-loading is set.
	Edges        FinanceClassEdges `json:"edges"`
	company_id   *int
	selectValues sql.SelectValues
}

// FinanceClassEdges holds the relations/edges for other nodes in the graph.
type FinanceClassEdges struct {
	// Company holds the value of the company edge.
	Company *CompanyDetail `json:"company,omitempty"`
	// Methods holds the value of the methods edge.
	Methods []*FinanceOperation `json:"methods,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int

	namedMethods map[string][]*FinanceOperation
}

// CompanyOrErr returns the Company value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FinanceClassEdges) CompanyOrErr() (*CompanyDetail, error) {
	if e.Company != nil {
		return e.Company, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: companydetail.Label}
	}
	return nil, &NotLoadedError{edge: "company"}
}

// MethodsOrErr returns the Methods value or an error if the edge
// was not loaded in eager-loading.
func (e FinanceClassEdges) MethodsOrErr() ([]*FinanceOperation, error) {
	if e.loadedTypes[1] {
		return e.Methods, nil
	}
	return nil, &NotLoadedError{edge: "methods"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FinanceClass) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case financeclass.FieldStatus:
			values[i] = new(sql.NullBool)
		case financeclass.FieldID:
			values[i] = new(sql.NullInt64)
		case financeclass.FieldCategory, financeclass.FieldName, financeclass.FieldDeletedName:
			values[i] = new(sql.NullString)
		case financeclass.FieldDeletedDate, financeclass.FieldCreatedAt, financeclass.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case financeclass.ForeignKeys[0]: // company_id
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FinanceClass fields.
func (_m *FinanceClass) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case financeclass.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case financeclass.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case financeclass.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case financeclass.FieldDeletedName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field DeletedName", values[i])
			} else if value.Valid {
				_m.DeletedName = value.String
			}
		case financeclass.FieldDeletedDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field DeletedDate", values[i])
			} else if value.Valid {
				_m.DeletedDate = value.Time
			}
		case financeclass.FieldStatus:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field Status", values[i])
			} else if value.Valid {
				_m.Status = value.Bool
			}
		case financeclass.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case financeclass.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updatedAt", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case financeclass.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field company_id", value)
			} else if value.Valid {
				_m.company_id = new(int)
				*_m.company_id = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FinanceClass.
// This includes values selected through modifiers, order, etc.
func (_m *FinanceClass) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCompany queries the "company" edge of the FinanceClass entity.
func (_m *FinanceClass) QueryCompany() *CompanyDetailQuery {
	return NewFinanceClassClient(_m.config).QueryCompany(_m)
}

// QueryMethods queries the "methods" edge of the FinanceClass entity.
func (_m *FinanceClass) QueryMethods() *FinanceOperationQuery {
	return NewFinanceClassClient(_m.config).QueryMethods(_m)
}

// Update returns a builder for updating this FinanceClass.
// Note that you need to call FinanceClass.Unwrap() before calling this method if this FinanceClass
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FinanceClass) Update() *FinanceClassUpdateOne {
	return NewFinanceClassClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FinanceClass entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FinanceClass) Unwrap() *FinanceClass {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FinanceClass is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FinanceClass) String() string {
	var builder strings.Builder
	builder.WriteString("FinanceClass(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("Category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("Name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("DeletedName=")
	builder.WriteString(_m.DeletedName)
	builder.WriteString(", ")
	builder.WriteString("DeletedDate=")
	builder.WriteString(_m.DeletedDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("Status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updatedAt=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NamedMethods returns the Methods named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *FinanceClass) NamedMethods(name string) ([]*FinanceOperation, error) {
	if _m.Edges.namedMethods == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedMethods[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *FinanceClass) appendNamedMethods(name string, edges ...*FinanceOperation) {
	if _m.Edges.namedMethods == nil {
		_m.Edges.namedMethods = make(map[string][]*FinanceOperation)
	}
	if len(edges) == 0 {
		_m.Edges.namedMethods[name] = []*FinanceOperation{}
	} else {
		_m.Edges.namedMethods[name] = append(_m.Edges.namedMethods[name], edges...)
	}
}

// FinanceClasses is a parsable slice of FinanceClass.
type FinanceClasses []*FinanceClass
