// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/polatbilal/ent-gqlgen/ent/companydetail"
	"github.com/polatbilal/ent-gqlgen/ent/financeaccount"
	"github.com/polatbilal/ent-gqlgen/ent/financeoperation"
)

// FinanceAccountCreate is the builder for creating a FinanceAccount entity.
type FinanceAccountCreate struct {
	config
	mutation *FinanceAccountMutation
	hooks    []Hook
}

// SetName sets the "Name" field.
func (_c *FinanceAccountCreate) SetName(v string) *FinanceAccountCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (_c *FinanceAccountCreate) SetNillableName(v *string) *FinanceAccountCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetCreatedAt sets the "createdAt" field.
func (_c *FinanceAccountCreate) SetCreatedAt(v time.Time) *FinanceAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_c *FinanceAccountCreate) SetNillableCreatedAt(v *time.Time) *FinanceAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updatedAt" field.
func (_c *FinanceAccountCreate) SetUpdatedAt(v time.Time) *FinanceAccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (_c *FinanceAccountCreate) SetNillableUpdatedAt(v *time.Time) *FinanceAccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCompanyID sets the "company" edge to the CompanyDetail entity by ID.
func (_c *FinanceAccountCreate) SetCompanyID(id int) *FinanceAccountCreate {
	_c.mutation.SetCompanyID(id)
	return _c
}

// SetNillableCompanyID sets the "company" edge to the CompanyDetail entity by ID if the given value is not nil.
func (_c *FinanceAccountCreate) SetNillableCompanyID(id *int) *FinanceAccountCreate {
	if id != nil {
		_c = _c.SetCompanyID(*id)
	}
	return _c
}

// SetCompany sets the "company" edge to the CompanyDetail entity.
func (_c *FinanceAccountCreate) SetCompany(v *CompanyDetail) *FinanceAccountCreate {
	return _c.SetCompanyID(v.ID)
}

// AddAccountIDs adds the "accounts" edge to the FinanceOperation entity by IDs.
func (_c *FinanceAccountCreate) AddAccountIDs(ids ...int) *FinanceAccountCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the FinanceOperation entity.
func (_c *FinanceAccountCreate) AddAccounts(v ...*FinanceOperation) *FinanceAccountCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// Mutation returns the FinanceAccountMutation object of the builder.
func (_c *FinanceAccountCreate) Mutation() *FinanceAccountMutation {
	return _c.mutation
}

// Save creates the FinanceAccount in the database.
func (_c *FinanceAccountCreate) Save(ctx context.Context) (*FinanceAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FinanceAccountCreate) SaveX(ctx context.Context) *FinanceAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FinanceAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FinanceAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FinanceAccountCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := financeaccount.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := financeaccount.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := financeaccount.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FinanceAccountCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "Name", err: errors.New(`ent: missing required field "FinanceAccount.Name"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "FinanceAccount.createdAt"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "FinanceAccount.updatedAt"`)}
	}
	return nil
}

func (_c *FinanceAccountCreate) sqlSave(ctx context.Context) (*FinanceAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FinanceAccountCreate) createSpec() (*FinanceAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &FinanceAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(financeaccount.Table, sqlgraph.NewFieldSpec(financeaccount.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(financeaccount.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(financeaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(financeaccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CompanyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   financeaccount.CompanyTable,
			Columns: []string{financeaccount.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(companydetail.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.company_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   financeaccount.AccountsTable,
			Columns: []string{financeaccount.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financeoperation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FinanceAccountCreateBulk is the builder for creating many FinanceAccount entities in bulk.
type FinanceAccountCreateBulk struct {
	config
	err      error
	builders []*FinanceAccountCreate
}

// Save creates the FinanceAccount entities in the database.
func (_c *FinanceAccountCreateBulk) Save(ctx context.Context) ([]*FinanceAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FinanceAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FinanceAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FinanceAccountCreateBulk) SaveX(ctx context.Context) []*FinanceAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FinanceAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FinanceAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
