// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/polatbilal/ent-gqlgen/ent/jobauthor"
	"github.com/polatbilal/ent-gqlgen/ent/jobrelations"
	"github.com/polatbilal/ent-gqlgen/ent/predicate"
)

// JobAuthorQuery is the builder for querying JobAuthor entities.
type JobAuthorQuery struct {
	config
	ctx              *QueryContext
	order            []jobauthor.OrderOption
	inters           []Interceptor
	predicates       []predicate.JobAuthor
	withAuthors      *JobRelationsQuery
	modifiers        []func(*sql.Selector)
	loadTotal        []func(context.Context, []*JobAuthor) error
	withNamedAuthors map[string]*JobRelationsQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the JobAuthorQuery builder.
func (_q *JobAuthorQuery) Where(ps ...predicate.JobAuthor) *JobAuthorQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *JobAuthorQuery) Limit(limit int) *JobAuthorQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *JobAuthorQuery) Offset(offset int) *JobAuthorQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *JobAuthorQuery) Unique(unique bool) *JobAuthorQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *JobAuthorQuery) Order(o ...jobauthor.OrderOption) *JobAuthorQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAuthors chains the current query on the "authors" edge.
func (_q *JobAuthorQuery) QueryAuthors() *JobRelationsQuery {
	query := (&JobRelationsClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(jobauthor.Table, jobauthor.FieldID, selector),
			sqlgraph.To(jobrelations.Table, jobrelations.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, jobauthor.AuthorsTable, jobauthor.AuthorsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first JobAuthor entity from the query.
// Returns a *NotFoundError when no JobAuthor was found.
func (_q *JobAuthorQuery) First(ctx context.Context) (*JobAuthor, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{jobauthor.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *JobAuthorQuery) FirstX(ctx context.Context) *JobAuthor {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first JobAuthor ID from the query.
// Returns a *NotFoundError when no JobAuthor ID was found.
func (_q *JobAuthorQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{jobauthor.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *JobAuthorQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single JobAuthor entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one JobAuthor entity is found.
// Returns a *NotFoundError when no JobAuthor entities are found.
func (_q *JobAuthorQuery) Only(ctx context.Context) (*JobAuthor, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{jobauthor.Label}
	default:
		return nil, &NotSingularError{jobauthor.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *JobAuthorQuery) OnlyX(ctx context.Context) *JobAuthor {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only JobAuthor ID in the query.
// Returns a *NotSingularError when more than one JobAuthor ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *JobAuthorQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{jobauthor.Label}
	default:
		err = &NotSingularError{jobauthor.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *JobAuthorQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of JobAuthors.
func (_q *JobAuthorQuery) All(ctx context.Context) ([]*JobAuthor, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*JobAuthor, *JobAuthorQuery]()
	return withInterceptors[[]*JobAuthor](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *JobAuthorQuery) AllX(ctx context.Context) []*JobAuthor {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of JobAuthor IDs.
func (_q *JobAuthorQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(jobauthor.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *JobAuthorQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *JobAuthorQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*JobAuthorQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *JobAuthorQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *JobAuthorQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *JobAuthorQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the JobAuthorQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *JobAuthorQuery) Clone() *JobAuthorQuery {
	if _q == nil {
		return nil
	}
	return &JobAuthorQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]jobauthor.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.JobAuthor{}, _q.predicates...),
		withAuthors: _q.withAuthors.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithAuthors tells the query-builder to eager-load the nodes that are connected to
// the "authors" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *JobAuthorQuery) WithAuthors(opts ...func(*JobRelationsQuery)) *JobAuthorQuery {
	query := (&JobRelationsClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAuthors = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		YibfNo int `json:"yibfNo,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.JobAuthor.Query().
//		GroupBy(jobauthor.FieldYibfNo).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *JobAuthorQuery) GroupBy(field string, fields ...string) *JobAuthorGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &JobAuthorGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = jobauthor.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		YibfNo int `json:"yibfNo,omitempty"`
//	}
//
//	client.JobAuthor.Query().
//		Select(jobauthor.FieldYibfNo).
//		Scan(ctx, &v)
func (_q *JobAuthorQuery) Select(fields ...string) *JobAuthorSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &JobAuthorSelect{JobAuthorQuery: _q}
	sbuild.label = jobauthor.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a JobAuthorSelect configured with the given aggregations.
func (_q *JobAuthorQuery) Aggregate(fns ...AggregateFunc) *JobAuthorSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *JobAuthorQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !jobauthor.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *JobAuthorQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*JobAuthor, error) {
	var (
		nodes       = []*JobAuthor{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withAuthors != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*JobAuthor).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &JobAuthor{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAuthors; query != nil {
		if err := _q.loadAuthors(ctx, query, nodes,
			func(n *JobAuthor) { n.Edges.Authors = []*JobRelations{} },
			func(n *JobAuthor, e *JobRelations) { n.Edges.Authors = append(n.Edges.Authors, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedAuthors {
		if err := _q.loadAuthors(ctx, query, nodes,
			func(n *JobAuthor) { n.appendNamedAuthors(name) },
			func(n *JobAuthor, e *JobRelations) { n.appendNamedAuthors(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *JobAuthorQuery) loadAuthors(ctx context.Context, query *JobRelationsQuery, nodes []*JobAuthor, init func(*JobAuthor), assign func(*JobAuthor, *JobRelations)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*JobAuthor)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.JobRelations(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(jobauthor.AuthorsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.author_id
		if fk == nil {
			return fmt.Errorf(`foreign-key "author_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "author_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *JobAuthorQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *JobAuthorQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(jobauthor.Table, jobauthor.Columns, sqlgraph.NewFieldSpec(jobauthor.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, jobauthor.FieldID)
		for i := range fields {
			if fields[i] != jobauthor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *JobAuthorQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(jobauthor.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = jobauthor.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedAuthors tells the query-builder to eager-load the nodes that are connected to the "authors"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *JobAuthorQuery) WithNamedAuthors(name string, opts ...func(*JobRelationsQuery)) *JobAuthorQuery {
	query := (&JobRelationsClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedAuthors == nil {
		_q.withNamedAuthors = make(map[string]*JobRelationsQuery)
	}
	_q.withNamedAuthors[name] = query
	return _q
}

// JobAuthorGroupBy is the group-by builder for JobAuthor entities.
type JobAuthorGroupBy struct {
	selector
	build *JobAuthorQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *JobAuthorGroupBy) Aggregate(fns ...AggregateFunc) *JobAuthorGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *JobAuthorGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JobAuthorQuery, *JobAuthorGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *JobAuthorGroupBy) sqlScan(ctx context.Context, root *JobAuthorQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// JobAuthorSelect is the builder for selecting fields of JobAuthor entities.
type JobAuthorSelect struct {
	*JobAuthorQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *JobAuthorSelect) Aggregate(fns ...AggregateFunc) *JobAuthorSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *JobAuthorSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JobAuthorQuery, *JobAuthorSelect](ctx, _s.JobAuthorQuery, _s, _s.inters, v)
}

func (_s *JobAuthorSelect) sqlScan(ctx context.Context, root *JobAuthorQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
