// Code generated by ent, DO NOT EDIT.

package financecurrentaccountgroup

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the financecurrentaccountgroup type in the database.
	Label = "finance_current_account_group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// EdgeCurrentAccounts holds the string denoting the current_accounts edge name in mutations.
	EdgeCurrentAccounts = "current_accounts"
	// Table holds the table name of the financecurrentaccountgroup in the database.
	Table = "current_account_groups"
	// CurrentAccountsTable is the table that holds the current_accounts relation/edge.
	CurrentAccountsTable = "current_accounts"
	// CurrentAccountsInverseTable is the table name for the FinanceCurrentAccount entity.
	// It exists in this package in order to avoid circular dependency with the "financecurrentaccount" package.
	CurrentAccountsInverseTable = "current_accounts"
	// CurrentAccountsColumn is the table column denoting the current_accounts relation/edge.
	CurrentAccountsColumn = "group_id"
)

// Columns holds all SQL columns for financecurrentaccountgroup fields.
var Columns = []string{
	FieldID,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the FinanceCurrentAccountGroup queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDescription orders the results by the Description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCurrentAccountsCount orders the results by current_accounts count.
func ByCurrentAccountsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCurrentAccountsStep(), opts...)
	}
}

// ByCurrentAccounts orders the results by current_accounts terms.
func ByCurrentAccounts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCurrentAccountsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCurrentAccountsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CurrentAccountsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CurrentAccountsTable, CurrentAccountsColumn),
	)
}
