-- Add new schema named "finance"
CREATE SCHEMA IF NOT EXISTS "finance";
-- Create index "company_details_company_code_key" to table: "company_details"
CREATE UNIQUE INDEX "company_details_company_code_key" ON "core"."company_details" ("company_code");
-- Create "operation_groups" table
CREATE TABLE "finance"."operation_groups" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "description" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "bank_accounts" table
CREATE TABLE "finance"."bank_accounts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "description" character varying NOT NULL,
  "deleted_description" character varying NULL,
  "deleted_date" timestamptz NULL,
  "status" boolean NOT NULL DEFAULT true,
  "company_id" bigint NULL,
  PRIMARY KEY ("id")
);
-- Create "bank_account_operations" table
CREATE TABLE "finance"."bank_account_operations" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "date" timestamptz NOT NULL,
  "debit" numeric(18,2) NULL,
  "credit" numeric(18,2) NULL,
  "description" character varying NOT NULL,
  "status" boolean NOT NULL DEFAULT true,
  "company_id" bigint NULL,
  "bank_account_id" bigint NULL,
  "participant_current_account_operation_id" bigint NULL,
  "participant_cash_account_operation_id" bigint NULL,
  "operation_group_id" bigint NULL,
  "payment_class_id" bigint NULL,
  PRIMARY KEY ("id")
);
-- Create "cash_account_operations" table
CREATE TABLE "finance"."cash_account_operations" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "date" timestamptz NOT NULL,
  "debit" numeric(18,2) NULL,
  "credit" numeric(18,2) NULL,
  "description" character varying NOT NULL,
  "status" boolean NOT NULL DEFAULT true,
  "company_id" bigint NULL,
  "operation_group_id" bigint NULL,
  "cash_account_id" bigint NULL,
  "participant_current_account_operation_id" bigint NULL,
  "participant_bank_account_operation_id" bigint NULL,
  "payment_class_id" bigint NULL,
  PRIMARY KEY ("id")
);
-- Create "cash_accounts" table
CREATE TABLE "finance"."cash_accounts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "description" character varying NOT NULL,
  "deleted_description" character varying NULL,
  "deleted_date" timestamptz NULL,
  "status" boolean NOT NULL DEFAULT true,
  "company_id" bigint NULL,
  PRIMARY KEY ("id")
);
-- Create "current_account_groups" table
CREATE TABLE "finance"."current_account_groups" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "description" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "current_account_operation_types" table
CREATE TABLE "finance"."current_account_operation_types" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "description" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "current_account_operations" table
CREATE TABLE "finance"."current_account_operations" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "date" timestamptz NOT NULL,
  "debit" numeric(18,2) NULL,
  "credit" numeric(18,2) NULL,
  "description" character varying NOT NULL,
  "status" boolean NOT NULL DEFAULT true,
  "company_id" bigint NULL,
  "operation_group_id" bigint NULL,
  "account_id" bigint NULL,
  "type_id" bigint NULL,
  PRIMARY KEY ("id")
);
-- Create "current_account_types" table
CREATE TABLE "finance"."current_account_types" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "description" character varying NOT NULL DEFAULT 'AÇIKLAMA YOK',
  "deleted_description" character varying NULL,
  "deleted_date" timestamptz NULL,
  "status" boolean NOT NULL DEFAULT true,
  "company_id" bigint NULL,
  PRIMARY KEY ("id")
);
-- Create "current_accounts" table
CREATE TABLE "finance"."current_accounts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL DEFAULT 'İSİM YOK',
  "deleted_name" character varying NULL,
  "national_identification_number" character varying NULL,
  "address" character varying NULL,
  "tax_office" character varying NULL,
  "tax_number" character varying NULL,
  "business_phone" character varying NULL,
  "cell_phone" character varying NULL,
  "fax" character varying NULL,
  "email" character varying NULL,
  "web_address" character varying NULL,
  "note" character varying NULL,
  "status" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "company_id" bigint NULL,
  "group_id" bigint NULL,
  "type_id" bigint NULL,
  PRIMARY KEY ("id")
);
-- Create "payment_classes" table
CREATE TABLE "finance"."payment_classes" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "description" character varying NOT NULL,
  "deleted_description" character varying NULL,
  "deleted_date" timestamptz NULL,
  "status" boolean NOT NULL DEFAULT true,
  "company_id" bigint NULL,
  PRIMARY KEY ("id")
);
-- Modify "company_engineers" table
ALTER TABLE "core"."company_engineers" ADD CONSTRAINT "company_engineers_company_details_engineers" FOREIGN KEY ("company_id") REFERENCES "core"."company_details" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "company_tokens" table
ALTER TABLE "core"."company_tokens" ADD CONSTRAINT "company_tokens_company_details_tokens" FOREIGN KEY ("company_id") REFERENCES "core"."company_details" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "company_users" table
ALTER TABLE "core"."company_users" ADD CONSTRAINT "company_users_company_details_users" FOREIGN KEY ("company_id") REFERENCES "core"."company_details" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "job_relations" table
ALTER TABLE "core"."job_relations" ADD CONSTRAINT "job_relations_company_details_jobs" FOREIGN KEY ("company_id") REFERENCES "core"."company_details" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "bank_accounts" table
ALTER TABLE "finance"."bank_accounts" ADD CONSTRAINT "bank_accounts_company_details_bank_accounts" FOREIGN KEY ("company_id") REFERENCES "core"."company_details" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "bank_account_operations" table
ALTER TABLE "finance"."bank_account_operations" ADD CONSTRAINT "bank_account_operations_bank_accounts_operations" FOREIGN KEY ("bank_account_id") REFERENCES "finance"."bank_accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "bank_account_operations_cash_account_operations_participant_cas" FOREIGN KEY ("participant_cash_account_operation_id") REFERENCES "finance"."cash_account_operations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "bank_account_operations_company_details_bank_operations" FOREIGN KEY ("company_id") REFERENCES "core"."company_details" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "bank_account_operations_current_account_operations_participant_" FOREIGN KEY ("participant_current_account_operation_id") REFERENCES "finance"."current_account_operations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "bank_account_operations_operation_groups_bank_operations" FOREIGN KEY ("operation_group_id") REFERENCES "finance"."operation_groups" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "bank_account_operations_payment_classes_bank_payments" FOREIGN KEY ("payment_class_id") REFERENCES "finance"."payment_classes" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "cash_account_operations" table
ALTER TABLE "finance"."cash_account_operations" ADD CONSTRAINT "cash_account_operations_bank_account_operations_participant_ban" FOREIGN KEY ("participant_bank_account_operation_id") REFERENCES "finance"."bank_account_operations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "cash_account_operations_cash_accounts_operations" FOREIGN KEY ("cash_account_id") REFERENCES "finance"."cash_accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "cash_account_operations_company_details_cash_operations" FOREIGN KEY ("company_id") REFERENCES "core"."company_details" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "cash_account_operations_current_account_operations_participant_" FOREIGN KEY ("participant_current_account_operation_id") REFERENCES "finance"."current_account_operations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "cash_account_operations_operation_groups_cash_operations" FOREIGN KEY ("operation_group_id") REFERENCES "finance"."operation_groups" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "cash_account_operations_payment_classes_cash_payments" FOREIGN KEY ("payment_class_id") REFERENCES "finance"."payment_classes" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "cash_accounts" table
ALTER TABLE "finance"."cash_accounts" ADD CONSTRAINT "cash_accounts_company_details_cash_accounts" FOREIGN KEY ("company_id") REFERENCES "core"."company_details" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "current_account_operations" table
ALTER TABLE "finance"."current_account_operations" ADD CONSTRAINT "current_account_operations_operation_groups_current_operations" FOREIGN KEY ("operation_group_id") REFERENCES "finance"."operation_groups" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "current_account_operations_company_details_current_operations" FOREIGN KEY ("company_id") REFERENCES "core"."company_details" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "current_account_operations_current_account_operation_types_curr" FOREIGN KEY ("type_id") REFERENCES "finance"."current_account_operation_types" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "current_account_operations_current_accounts_operations" FOREIGN KEY ("account_id") REFERENCES "finance"."current_accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "current_account_types" table
ALTER TABLE "finance"."current_account_types" ADD CONSTRAINT "current_account_types_company_details_current_account_types" FOREIGN KEY ("company_id") REFERENCES "core"."company_details" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "current_accounts" table
ALTER TABLE "finance"."current_accounts" ADD CONSTRAINT "current_accounts_company_details_current_accounts" FOREIGN KEY ("company_id") REFERENCES "core"."company_details" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "current_accounts_current_account_groups_current_accounts" FOREIGN KEY ("group_id") REFERENCES "finance"."current_account_groups" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "current_accounts_current_account_types_current_accounts" FOREIGN KEY ("type_id") REFERENCES "finance"."current_account_types" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "payment_classes" table
ALTER TABLE "finance"."payment_classes" ADD CONSTRAINT "payment_classes_company_details_cash_payment_classes" FOREIGN KEY ("company_id") REFERENCES "core"."company_details" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "job_payments" table
ALTER TABLE "core"."job_payments" ALTER COLUMN "amount" TYPE numeric(18,2), ALTER COLUMN "invoice_received_amount" TYPE numeric(18,2), ADD COLUMN "invoice_number" character varying NULL, ADD COLUMN "withholding" boolean NULL DEFAULT false;
